plugins {
    id 'java'
}

group = 'ro.vladlautaru'
version = '0.2.0-alpha'

tasks.register('clientJar', Jar) {
    archiveBaseName = 'client'
    archiveVersion = ''
    manifest {
        attributes(
                'Main-Class': 'io.vladlautaru.client.ClientMain'
        )
    }
    from sourceSets.main.output
    destinationDirectory = file('jar')
}

tasks.register('serverJar', Jar) {
    archiveBaseName = 'server'
    archiveVersion = ''
    manifest {
        attributes(
                'Main-Class': 'io.vladlautaru.server.ServerMain'
        )
    }
    from sourceSets.main.output
    destinationDirectory = file('jar')
}

assemble.dependsOn clientJar, serverJar

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}